package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/lambda/apps/subgraph-auth/graph/generated"
	"github.com/lambda/apps/subgraph-auth/graph/model"
)

// InviteUser is the resolver for the inviteUser field.
func (r *mutationResolver) InviteUser(ctx context.Context, email string, role string) (*model.TokenResponse, error) {
	// MOCK: Normally this would call InvitationService
	mockToken := "mock-jwt-token-for-" + email
	return &model.TokenResponse{Token: &mockToken}, nil
}

// ValidateInvite is the resolver for the validateInvite field.
func (r *mutationResolver) ValidateInvite(ctx context.Context, token string) (*string, error) {
	// MOCK: validation logic
	if token == "invalid" {
		return nil, fmt.Errorf("invalid token")
	}
	msg := "Token is valid (MOCK)"
	return &msg, nil
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, email string, password string, role string, tenantID string, navigatorAdminID string) (*string, error) {
	// MOCK: Cognito registration
	sub := "mock-user-sub-12345"
	return &sub, nil
}

// SendOtp is the resolver for the sendOtp field.
func (r *mutationResolver) SendOtp(ctx context.Context, email string, password string) (*model.SessionResponse, error) {
	// MOCK: Start OTP
	session := "mock-session-id-555"
	return &model.SessionResponse{Session: &session}, nil
}

// VerifyOtp is the resolver for the verifyOtp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string, session string) (*model.AuthResponse, error) {
	// MOCK: Verify OTP
	if otp != "123456" {
		return nil, fmt.Errorf("invalid OTP")
	}

	accessToken := "mock-access-token"
	idToken := "mock-id-token"
	refreshToken := "mock-refresh-token"

	return &model.AuthResponse{
		AccessToken:  &accessToken,
		IDToken:      &idToken,
		RefreshToken: &refreshToken,
	}, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, email string, password string) (*model.SessionResponse, error) {
	// MOCK: Login
	session := "mock-session-id-login-999"
	return &model.SessionResponse{Session: &session}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*string, error) {
	status := "ok"
	return &status, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }