// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BarrierCount struct {
	Month        string  `json:"month"`
	ProblemName  string  `json:"problemName"`
	BarrierCount float64 `json:"barrierCount"`
}

type BarrierFilters struct {
	Year         *string  `json:"year,omitempty"`
	Disease      *string  `json:"disease,omitempty"`
	Type         *string  `json:"type,omitempty"`
	Month        *string  `json:"month,omitempty"`
	CreatedBy    *string  `json:"createdBy,omitempty"`
	CreatedByIds []string `json:"createdByIds,omitempty"`
}

type BarrierResponse struct {
	ChartData   []*BarrierCount   `json:"chartData"`
	SubtypeData []*BarrierSubtype `json:"subtypeData"`
}

type BarrierSubtype struct {
	SubType      string `json:"subType"`
	BarrierCount int    `json:"barrierCount"`
}

type CreateInterventionsInput struct {
	PatientID    string                   `json:"patientId"`
	ScreeningID  string                   `json:"screeningId"`
	Items        []*InterventionItemInput `json:"items"`
	NotifyPeople []string                 `json:"notifyPeople,omitempty"`
	CreatedFrom  *string                  `json:"createdFrom,omitempty"`
}

type CreateInterventionsResponse struct {
	InterventionIds []string       `json:"interventionIds"`
	CreatedTasks    []*CreatedTask `json:"createdTasks"`
}

type CreatedTask struct {
	TaskID       string `json:"taskId"`
	AssigneeRole string `json:"assigneeRole"`
}

type Intervention struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenantId"`
	PatientID       string             `json:"patientId"`
	ScreeningID     string             `json:"screeningId"`
	Type            InterventionType   `json:"type"`
	Title           string             `json:"title"`
	Description     *string            `json:"description,omitempty"`
	Status          InterventionStatus `json:"status"`
	Priority        string             `json:"priority"`
	CreatedBy       string             `json:"createdBy"`
	AssignedTo      *string            `json:"assignedTo,omitempty"`
	AssignedTeam    *string            `json:"assignedTeam,omitempty"`
	DueAt           *string            `json:"dueAt,omitempty"`
	CompletedAt     *string            `json:"completedAt,omitempty"`
	LinkedTaskID    *string            `json:"linkedTaskId,omitempty"`
	ReferralReasons []string           `json:"referralReasons,omitempty"`
	Problems        []string           `json:"problems,omitempty"`
	Notes           *string            `json:"notes,omitempty"`
	CreatedAt       string             `json:"createdAt"`
	UpdatedAt       string             `json:"updatedAt"`
	User            *User              `json:"user,omitempty"`
}

type InterventionFilters struct {
	Status       *InterventionStatus `json:"status,omitempty"`
	Type         *InterventionType   `json:"type,omitempty"`
	AssignedTeam *string             `json:"assignedTeam,omitempty"`
	PatientID    *string             `json:"patientId,omitempty"`
	ScreeningID  *string             `json:"screeningId,omitempty"`
	ScreeningIds []string            `json:"screeningIds,omitempty"`
	CreatedBy    *string             `json:"createdBy,omitempty"`
	CreatedByIds []string            `json:"createdByIds,omitempty"`
}

type InterventionItemInput struct {
	Type            InterventionType `json:"type"`
	Title           string           `json:"title"`
	ScheduleInDay   *string          `json:"scheduleInDay,omitempty"`
	DueInDay        *string          `json:"dueInDay,omitempty"`
	ReferralReasons []string         `json:"referralReasons,omitempty"`
	Problems        []string         `json:"problems,omitempty"`
	AssignedTo      *string          `json:"assignedTo,omitempty"`
	AssignedTeam    *string          `json:"assignedTeam,omitempty"`
	Priority        *string          `json:"priority,omitempty"`
	Description     *string          `json:"description,omitempty"`
}

type InterventionList struct {
	Interventions []*Intervention `json:"interventions"`
	Total         int             `json:"total"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateInterventionInput struct {
	AssignedTo   *string  `json:"assignedTo,omitempty"`
	AssignedTeam *string  `json:"assignedTeam,omitempty"`
	Priority     *string  `json:"priority,omitempty"`
	Notes        *string  `json:"notes,omitempty"`
	Problems     []string `json:"problems,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	TenantID  string `json:"tenantId"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type InterventionStatus string

const (
	InterventionStatusPending    InterventionStatus = "pending"
	InterventionStatusInProgress InterventionStatus = "in_progress"
	InterventionStatusCompleted  InterventionStatus = "completed"
	InterventionStatusCancelled  InterventionStatus = "cancelled"
)

var AllInterventionStatus = []InterventionStatus{
	InterventionStatusPending,
	InterventionStatusInProgress,
	InterventionStatusCompleted,
	InterventionStatusCancelled,
}

func (e InterventionStatus) IsValid() bool {
	switch e {
	case InterventionStatusPending, InterventionStatusInProgress, InterventionStatusCompleted, InterventionStatusCancelled:
		return true
	}
	return false
}

func (e InterventionStatus) String() string {
	return string(e)
}

func (e *InterventionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterventionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterventionStatus", str)
	}
	return nil
}

func (e InterventionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterventionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterventionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterventionType string

const (
	InterventionTypeFinancialCounselor   InterventionType = "financial_counselor"
	InterventionTypeSocialWork           InterventionType = "social_work"
	InterventionTypeRegisteredDietitian  InterventionType = "registered_dietitian"
	InterventionTypeSpiritualCare        InterventionType = "spiritual_care"
	InterventionTypeGeneticCounselor     InterventionType = "genetic_counselor"
	InterventionTypeRehabilitation       InterventionType = "rehabilitation"
	InterventionTypeClinicalTrial        InterventionType = "clinical_trial"
	InterventionTypeTranslationServices  InterventionType = "translation_services"
	InterventionTypePalliativeCare       InterventionType = "palliative_care"
	InterventionTypeHospice              InterventionType = "hospice"
	InterventionTypeSurvivorship         InterventionType = "survivorship"
	InterventionTypeCommunityResource    InterventionType = "community_resource"
	InterventionTypeCoordinationOfCare   InterventionType = "coordination_of_care"
	InterventionTypePhysicianOfficeStaff InterventionType = "physician_office_staff"
	InterventionTypeOther                InterventionType = "other"
)

var AllInterventionType = []InterventionType{
	InterventionTypeFinancialCounselor,
	InterventionTypeSocialWork,
	InterventionTypeRegisteredDietitian,
	InterventionTypeSpiritualCare,
	InterventionTypeGeneticCounselor,
	InterventionTypeRehabilitation,
	InterventionTypeClinicalTrial,
	InterventionTypeTranslationServices,
	InterventionTypePalliativeCare,
	InterventionTypeHospice,
	InterventionTypeSurvivorship,
	InterventionTypeCommunityResource,
	InterventionTypeCoordinationOfCare,
	InterventionTypePhysicianOfficeStaff,
	InterventionTypeOther,
}

func (e InterventionType) IsValid() bool {
	switch e {
	case InterventionTypeFinancialCounselor, InterventionTypeSocialWork, InterventionTypeRegisteredDietitian, InterventionTypeSpiritualCare, InterventionTypeGeneticCounselor, InterventionTypeRehabilitation, InterventionTypeClinicalTrial, InterventionTypeTranslationServices, InterventionTypePalliativeCare, InterventionTypeHospice, InterventionTypeSurvivorship, InterventionTypeCommunityResource, InterventionTypeCoordinationOfCare, InterventionTypePhysicianOfficeStaff, InterventionTypeOther:
		return true
	}
	return false
}

func (e InterventionType) String() string {
	return string(e)
}

func (e *InterventionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterventionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterventionType", str)
	}
	return nil
}

func (e InterventionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterventionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterventionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
