// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AccessToken  *string `json:"accessToken,omitempty"`
	IDToken      *string `json:"idToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SessionResponse struct {
	Session *string `json:"session,omitempty"`
}

type TokenResponse struct {
	Token *string `json:"token,omitempty"`
}
